config/routes.rb
Planitshareit::Application.routes.draw do
  resources :trips do
    resources :events
    resources :albums do
      resources :images
    end
  end
  
  match 'trips/:trip_id/driving' => "driving_directions#index", :as => "driving"
  match 'trips/:trip_id/day/:day/driving' => "driving_directions#index", :as => "driving"
  match 'public/trips/:trip_id' => "albums#index"
  
  root :to => "pages#index"
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'login' }
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates_presence_of :destination
  validates_presence_of :start_date
  validates_presence_of :end_date
  
  has_many :events
  has_many :albums

  belongs_to :user

  default_scope where(:status => 'active')

  before_create :set_title
  before_save :trip_geocode
  before_validation :time_add
  
  attr_accessor :no_accomodation
  
  def starting_location
	loc = {}
	loc['address'] = self.accomodation_address.blank? ? 
				self.destination_city + ', ' + self.destination_state :
				self.accomodation_address + ' ' + self.accomodation_city + ', ' + self.accomodation_state + ' ' + self.accomodation_zip,
	loc['latlng'] = !self.accomodation_latitude.blank? ?
				self.accomodation_latitude.to_s + ", " + self.accomodation_longitude.to_s :
				self.latitude.to_s + ", " + self.longitude.to_s
	loc['name'] = self.accomodation_address.blank? && self.accomodation_latitude.blank? ?
				self.destination : self.accomodation_name
	loc
  end
  
  def days
    (start_date.to_date..end_date.to_date).to_a
  end
  
  def events_on_day(day, type='all')
	case type
	when 'mapped'
		events = self.events.mapped
	when 'unmapped'
		events = self.events.unmapped
	else
		events = self.events
	end
	
	events.for_date(self.start_date.to_date + (day - 1).days)
  end

  private

  def set_title
    self.title = "#{destination_city} #{start_date.year}"
  end
  
  def trip_geocode
	geocode = Geokit::Geocoders::GoogleGeocoder.geocode(self.destination)
	if geocode.success?
		self.latitude=geocode.lat
		self.longitude=geocode.lng
		self.destination_city = geocode.city
		self.destination_state = geocode.state
		self.destination_zip = geocode.zip
	end
	
	accom_geocode = Geokit::Geocoders::GoogleGeocoder.geocode(self.accomodation_name + ' ' + self.destination_city + ', ' + self.destination_state)
	if accom_geocode.success? and !accom_geocode.street_address.blank?
		self.accomodation_address = accom_geocode.street_address
		self.accomodation_city = accom_geocode.city
		self.accomodation_state = accom_geocode.state
		self.accomodation_zip = accom_geocode.zip
		self.accomodation_latitude=accom_geocode.lat
		self.accomodation_longitude=accom_geocode.lng
	end
	self
  end
  
  def time_add
	self.start_date = self.start_date.to_s + ' 00:00:00'
	self.end_date = self.end_date.to_s  + ' 00:00:00'
	self
  end
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate_user!
    require 'geokit'

  def index
    # TODO Should be users' trips
    @trips = user_signed_in? ? current_user.trips : []
  end

  def show
    @trip = Trip.find(params[:id])

  	@starting_location = @trip.starting_location
  	authorize! :view, @trip
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(params[:trip])
    if @trip.save
      redirect_to @trip, :notice => 'Trip created.'
    else
      render :action => :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
	authorize! :edit, @trip

  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update_attributes(params[:trip])
      redirect_to @trip, :notice => 'Trip successfully updated.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.status = 'deleted'
    @trip.save

    redirect_to(trips_url)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_day_listing.html.erb
<div class="daily-view">
	<div class="days items">
		<% @trip.days.each do |day| %>
		<div class="day item">
			<div class="head"><%= day.strftime("%B %d") %></div>
			<div class="body">
				<% events = @trip.events.for_date(day.strftime("%Y-%m-%d")) %>
				<% column_1 = events[0...(events.size/2.0).ceil] %>
				<% column_2 = events[(events.size/2.0).ceil...events.size] %>
				<div class='col-1'>
					<%= render :partial => 'events/event_full', :collection => column_1 %>
				</div>
				<div class='col-2'>
					<%= render :partial => 'events/event_full', :collection => column_2 %>
				</div>
				<div style="clear:both"></div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/trips/_day_overview.html.erb
<div class="overview scrollable">
	<div class="items">
		<% @trip.days.each_slice(4) do |day_array| %>
		<ul class="days item">
			<% day_array.each do |day| %>
			<li class="day<%= ' first' if day == day_array[0] %><%= ' last' if day == day_array[3] %>">
				<div class="head"><%= day.strftime("%B %d") %></div>
				<div class="body">
					<%= render :partial => 'events/event_tiny', :collection => @trip.events.for_date(day) %>
				</div>
			</li>
			<% end %>
		</ul>
		<% end %>
	</div>
</div>

app/views/trips/_unscheduled_events.html.erb
	<div class="top"><strong>Tell us when...</strong></div>
	<div>
		<% events = @trip.events.unscheduled %>
		<% column_1 = events[0...(events.size/2.0).ceil] %>
		<% column_2 = events[(events.size/2.0).ceil...events.size] %>
		<div class='col-1'>
			<%= render :partial => 'events/event_full', :collection => column_1 %>
		</div>
		<div class='col-2'>
			<%= render :partial => 'events/event_full', :collection => column_2 %>
		</div>
		<div style="clear:both"></div>
	</div>

app/views/trips/index.html.erb
<div id="trip-list">
	<h1>Your Trips!</h1>
	<% @trips.each do |trip| %>
	  <div class="trip">
		<div class="public-url">
			<span>Share this URL with your friends:</span>
			<div>
				http://<%= request.host %>/public/trips/<%= trip.id %>
			</div>
		</div>
	  	<h2><%= link_to trip.title, trip %></h2>
		<h3><%= trip.start_date.strftime('%b %d, %Y') %> - <%= trip.end_date.strftime('%b %d, %Y') %> | <%= trip.destination %></h3>
	  </div>
	<% end %>
</div>

app/views/trips/new.html.erb
<% if false #@trip.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

    <ul>
    <% @trip.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% form_for @trip do |f| %>
  <!-- User -->
  <%= image_tag('create-trip-header.png') %><br /><br />
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <dl>
    <!-- Destination -->
    <dt id="destination">Destination</dt>
    <dd id="destination_dd">
		<div>
		  <% if @trip.errors['destination'] %>
			<div class="error"><%= @trip.errors.full_messages[@trip.errors.keys.index(:destination)] %></div>
		  <% end %>

		  <%= f.label :destination, 'Where are you going?' %>
		  <%= f.text_field :destination, {:placeholder => "City, State"} %>
		</div>
	  <a href="#" class="next"><%= image_tag('next-button.png') %></a>
    </dd>

    <!-- Duration -->
    <dt id="duration">Duration</dt>
    <dd id="duration_dd">
      <% ['start_date', 'end_date'].each do |error| %>
        <%= content_tag 'div', @trip.errors.full_messages[@trip.errors.keys.index(error.to_sym)] if @trip.errors[error] %>
      <% end %>

      <table class="duration" border="0" cellspacing="0" cellpadding="4">
		<tr>
			<td align="right"><%= f.label :start_date, "When are you going?" %></td>
			<td><%= f.text_field :start_date, {:placeholder => "Select a date"} %></td>
        </tr>
		<tr>
			<td align="right"><%= f.label :end_date, "When are you coming back?" %></td>
			<td><%= f.text_field :end_date, {:placeholder => "Select a date"} %></td>
		</tr>
      </table>

      <a href="#" class="next"><%= image_tag('next-button.png') %></a>
    </dd>

    <!-- Travel Info -->
<!--    <dt>Travel Info</dt>
    <dd>
      <%= f.label :departure_city %>
      <%= f.text_field :departure_city %><br />

      <%= f.label :departure_time %>
      <%= f.text_field :departure_time %><br />

      <%= f.label :arrival_city %>
      <%= f.text_field :arrival_city %><br />

      <%= f.label :arrival_time %>
      <%= f.text_field :arrival_time %>

      <a href="#" class="prev">Previous</a>
      <a href="#" class="next">Continue</a>
    </dd>
-->
    <!-- Accomodations -->
    <dt id="accomodation">Accomodations</dt>
    <dd id="accomodation_dd">
	
		<div>
			<%= f.label :accomodation_name, "Where are you staying?" %>
			<%= f.text_field :accomodation_name, {:placeholder=>"Hotel Name, Address"} %>
			<br /><br />
			<div style="margin:0; padding:0 0 0 170px">
			<%= f.check_box :no_accomodation %>
			<%= f.label :no_accomodation, "I don't know yet" %>
			</div>
		</div>

      <%= image_submit_tag('create-trip-button.png', :class=>"next") %>
    </dd>
  </dl>
<% end %>
<div id="trip_intro">
	<p>You can choose to keep your profile and keep all of the cool stuff to yourself, or make it public and share your experiences with the world.</p>
</div>
<br /><br />

app/views/trips/show.html.erb
<div id="sidebar">
  <div id="share_it">
    <%= link_to image_tag("share-it.png"), trip_albums_path(@trip) %>
  </div>

  
</div>
<div id="trip-head">
	<h1><%= @trip.title %></h1>
	<h2><%= @trip.destination_city.blank? ? @trip.destination : @trip.destination_city + ', ' + @trip.destination_state %></h2>
</div>
<div id="trip-map">
	<div id="map_canvas" style="width:690px; height:450px;"></div>
</div>
<div id="trip-info">
	<div id="side_links">
	  <div class="button"><a href="<%= new_trip_event_path(@trip) %>" class="add_event" rel="#event-form-overlay">Add Event</a></div>
	  <div class="button"><%= link_to "Driving Directions", trip_path(@trip) + '/driving' %></div>
	</div>
	<div id="itenerary">
		<h3><%= image_tag 'your-itinerary.png' %></h3>
		

		<div class="nav">
			<%= image_tag "left-arrow.png", {:class => 'back prev browse right'} %>
			<%= image_tag "left-arrow.png", {:id => 'prev-day', :class => 'back browse right swapped'} %>
			<ul class="tabs">
				<li class="overview"></li>
				<li class="daily"></li>
			</ul>
			<%= image_tag 'right-arrow.png', {:class => 'forward next browse left'} %>
			<%= image_tag "right-arrow.png", {:id => 'next-day', :class => 'forward browse left swapped'} %>
		</div>
		<div style="clear: left;"></div>
		<div class="tab-panes">
			<%= render :partial => 'day_overview' %>
			<%= render :partial => 'day_listing' %>
		</div>
		<div class="unscheduled-events">
		<%= render :partial => 'unscheduled_events' %>
		</div>
	</div>
	
</div>


<script type="text/javascript">

var geocoder;
var map;
var marker;
   
function initialize(){
  var latlng = new google.maps.LatLng(<%= @starting_location['latlng'] %>);
  var options = {
    scrollwheel: false,
    zoom: 11,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
       
  map = new google.maps.Map(document.getElementById("map_canvas"), options);
       
  //GEOCODER
  geocoder = new google.maps.Geocoder();
    var bounds = new google.maps.LatLngBounds();

	  var mainMarker = new google.maps.Marker({
        position: latlng, 
        map: map, 
        title:"<%= @starting_location['name'] %>"
	  });
	<% unless @trip.events.mapped.blank? %>
	   bounds.extend(latlng);
       map.fitBounds(bounds);
	<% end %> 
    <% @trip.events.mapped.each do |place| %>
	  myLatLng = new google.maps.LatLng(<%= place.latitude %>, <%= place.longitude %>);
	  var marker = new google.maps.Marker({
        position: myLatLng, 
        map: map, 
        title:"<%= place.title %>"
	  }); 
      bounds.extend(myLatLng);
      map.fitBounds(bounds);
    <% end %>
  
  $("#map_canvas").append('<span class="hide_map"><a href="javascript://" id="hide_map_link">hide map</a></span>');
}

$(document).ready(function() {
         
  initialize();
  
  $("#hide_map_link").toggle(function(){
	$("#map_canvas").elapsor({
      color:'#fff',
      opacity:70
	});
	$("#map_canvas").animate({height:"50px"},1000);
	$("#map_canvas span a").html("show map");
  }, function(){
	$("#map_canvas").hideElapsor();
	$("#map_canvas").animate({height:"450px"},1000);
	$("#map_canvas span a").html("hide map");
  });
  
});

</script>

<div id="event-form-overlay" class="overlay" style="display:none">
	<!-- the external content is loaded inside this tag -->
	<div class="contentWrap"></div>

</div>


<script type="text/javascript" charset="utf-8">
	$(function() {
		$('ul.tabs').tabs('#itenerary div.tab-panes > div', {
			onClick: function  () {
				if (this.getIndex() == 0) {
					$('.browse.right').addClass('swapped');
					$('.browse.left').addClass('swapped');
					$('#prev-day').removeClass('swapped');
					$('#next-day').removeClass('swapped');
				} else {
					$('.browse.right').removeClass('swapped');
					$('.browse.left').removeClass('swapped');
					$('#prev-day').addClass('swapped');
					$('#next-day').addClass('swapped');
				}
				
			}
		});

		$('div.contentWrap form').live('submit', function () {
			var action = $(this).attr('action');
			$.post(action, $(this).serialize());
			return false;
		});

		$("a[rel]").live('click', function(e) {
			e.preventDefault();
			$(this).overlay({
				mask: 'black',
				closeOnClick: false,
				load: true,
				onBeforeLoad: function() {
					// grab wrapper element inside content
					var wrap = this.getOverlay().find(".contentWrap");
					// load the page specified in the trigger
					wrap.load(this.getTrigger().attr("href"));
					$open_overlay = this;
				},
				onClose: function() {
					reset_form('.event_form');
				}
			});
		});
	});
</script>