config/routes.rb
Planitshareit::Application.routes.draw do
  resources :trips do
    resources :events
    resources :albums do
      resources :images
    end
  end
  
  match 'trips/:trip_id/driving' => "driving_directions#index", :as => "driving"
  match 'trips/:trip_id/day/:day/driving' => "driving_directions#index", :as => "driving"
  match 'public/trips/:trip_id' => "albums#index"
  
  root :to => "pages#index"
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'login' }
end

app/controllers/driving_directions_controller.rb
class DrivingDirectionsController < ApplicationController
	def index
		@trip = Trip.find(params[:trip_id])
		@day = params[:day].blank? ? 1 : params[:day]
		@mapped_events = @trip.events_on_day(@day.to_i,'mapped')
		@unmapped_events = @trip.events_on_day(@day.to_i,'unmapped')
		@starting_location = @trip.starting_location
	end
end

app/helpers/driving_directions_helper.rb
module DrivingDirectionsHelper
end

app/views/driving_directions/index.html.erb
<div id="printDirections" style="float:right;padding-right:30px"><a href="javascript://" onclick="window.print()" style="border:0;outline:0"><%= image_tag('print-directions.png', :style=>"border:0;") %></a></div>

<div style=" margin-left:20px">

<h1>Driving Directions</h1>
<p style="width:670px;">
<%= link_to "Prev Day", driving_path(@trip, @day.to_i-1) unless @day == '1' %>&nbsp|&nbsp;
<%= @trip.start_date.to_date + (@day.to_i-1).days %>&nbsp;|&nbsp;
<%= link_to "Next Day", driving_path(@trip, @day.to_i+1) %>&nbsp;|&nbsp;<%= link_to "Return to Itinerary" , trip_path(@trip)%>
</p>

<% if !@mapped_events.blank? %>
<div id="event_listing" style="float:right; padding-right:25px">

<%= image_tag('events.png') %>
<% if !@mapped_events.blank? %> 
<p style="width:250px">Drag and Drop events to change their order in the directions.</p>
	<ul class="start_point">
		<li><%= @starting_location['name'] %></li>
	</ul>

	<ul id="sortable">
	<% @mapped_events.each do |e| %>
		<li id="e_<%= e.id %>" class="handle"><%= !e.title.blank? ? e.title : e.location %><span class="lat_long" style="display:none"><%= e.location %></span></li>
	<% end %>
	</ul>
<% end %>

<br />
<% if !@unmapped_events.blank? %>
Unmappable Events:
<ul>
<% @unmapped_events.each do |e| %>
	<li id="e_<%= e.id %>" class="handle"><%= !e.title.blank? ? e.title : e.location %><span class="lat_long" style="display:none"><%= e.location %></span></li>
<% end %>
</ul>
<% end %>
</div>





	<div id="map_canvas" style="width:640px; height:380px; float:left;"></div>
	<div id="directionsPanel" style="float:left;width:640px;"></div>
<% end %>

<br /><br />
</div>

<div style="clear:both"></div><br /><br />
<script type="text/javascript">

  var directionsDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;
  var geocoder;
  
  
  function initialize() {
    directionsDisplay = new google.maps.DirectionsRenderer();

    var latlng = new google.maps.LatLng(<%= @starting_location['latlng'] %>);
    var myOptions = {
	  scrollwheel: false,
      zoom: 11,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    
	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
	var mainMarker = new google.maps.Marker({
        position: latlng, 
        map: map, 
        title:"<%= @starting_location['name'] %>",
		center: latlng
	  }); 
	  
	directionsDisplay.setMap(map);
    directionsDisplay.setPanel(document.getElementById("directionsPanel"));
	
	geocoder = new google.maps.Geocoder();
	
	
	
	
/*****************	
	<% @trip.events_on_day(@day.to_i).each do |e| %>
	  myLatLng = new google.maps.LatLng(<%= e.latitude.to_s + ", " + e.longitude.to_s %>);
	  var marker = new google.maps.Marker({
        position: myLatLng, 
        map: map, 
        title:"<%= e.title %>"
	  }); 
	<% end %>
********************/
  }
  
  
  function calcRoute() {

    var start = '<%= @starting_location['latlng'] %>';
    var waypts = [];
	
    $("#sortable li").each(function(){
			waypts.push({
				location:$('.lat_long', this).html(),
				stopover:true
		})
	});
        
      
    

    var request = {
        origin: start, 
        destination: start,
        waypoints: waypts,
        optimizeWaypoints: false,
        travelMode: google.maps.DirectionsTravelMode.DRIVING
    };
	
	
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
	}});
        
		
/*		var route = response.routes[0];
        var summaryPanel = document.getElementById("directions_panel");
        summaryPanel.innerHTML = "";
        // For each route, display summary information.
        for (var i = 0; i < route.legs.length; i++) {
          var routeSegment = i + 1;
          summaryPanel.innerHTML += "<b>Route Segment: " + routeSegment + "</b><br />";
          summaryPanel.innerHTML += route.legs[i].start_address + " to ";
          summaryPanel.innerHTML += route.legs[i].end_address + "<br />";
          summaryPanel.innerHTML += route.legs[i].distance.text + "<br /><br />";
*/

  }
  
  


  
  $(function(){
 <% if !@mapped_events.blank? %> 
	initialize();
	calcRoute();
  <% end %>
	$(function() {
		$("#sortable").sortable({ 
			update : function () { 
				var order = $('#sortable').sortable('serialize'); 
				calcRoute();
			} 
		});

	});

	
  });
</script>