config/routes.rb
Planitshareit::Application.routes.draw do
  resources :trips do
    resources :events
    resources :albums do
      resources :images
    end
  end
  
  match 'trips/:trip_id/driving' => "driving_directions#index", :as => "driving"
  match 'trips/:trip_id/day/:day/driving' => "driving_directions#index", :as => "driving"
  match 'public/trips/:trip_id' => "albums#index"
  
  root :to => "pages#index"
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'login' }
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :trip
  has_many :images

  validates_presence_of :title
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :load_trip

  def index
    @albums = @trip.albums
    @viewer_is_owner = user_signed_in? && (@trip.user.username == current_user.username)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = @trip.albums.new
    authorize! :create, @album

    render :layout => false
  end

  def create
    @album = @trip.albums.new(params[:album])

    if @album.save
      redirect_to [@trip, @album], :notice => 'Album successfully created.'
    else
      redirect_to @trip, :alert => 'Your album could not be saved.'
    end
  end

  def edit
    @album = Album.find(params[:id])

    render :layout => false
  end

  def update
    @album = Album.find(params[:id])
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to(trip_albums_url(@trip))
  end

  private

  def load_trip
    @trip = Trip.find(params[:trip_id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<div class="album">
  <div class="image">
  <%= link_to image_tag(album.images.first.file.thumb.url, :width => 165, :height => 125), [@trip, album] unless album.images.empty? %>
  </div>

  <div class="album_info">
    <div class="title"><%= link_to album.title, [@trip, album] %></div>
    <div class="album_stats">
      <%= album.images.count %> Photos | <%= album.created_at.strftime '%B %d, %Y' %>
    </div>
  </div>
</div>

app/views/albums/_form.html.erb
<div class="errors">
  The following errors prevented the album from being saved:
  <ul class="error_list"></ul>
</div>

<table>
  <tr>
    <th><%= f.label :title %></th>
	  <td><%= f.text_field :title %></td>
  </tr>

  <tr>
    <th></th>
	  <td><%= image_submit_tag 'create-album.png' %></td>
	</tr>
</table>

app/views/albums/create.js.erb
<% if @album.save %>
  $open_overlay.close();
  $("div.albums").html("<%= escape_javascript(render(@trip.albums))%>");
  success('Album successfully created.');
<% else %>
  $('#<%= @album.errors.keys.map {|x| "album_#{x.to_s}" }.join(",#") %>').addClass('field_with_error');
  $('.album_form .error_list').html("<%= raw @album.errors.full_messages.map {|x| "<li>#{x}</li>"}.join %>");
  $('.album_form .errors').show();
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', [@trip, @album] %> |
<%= link_to 'Back', trip_albums_path(@trip) %>

app/views/albums/index.html.erb
<style type="text/css">
#content {
  min-height: 600px;
}
</style>
<%= javascript_include_tag 'album_form.js' %>
<div id="sidebar">
  <% if @viewer_is_owner %>
  <div id="share_it">
    <%= link_to image_tag("plan-it.png"), trip_url(@trip) %>
  </div>
  
  <div class="button"><a href="<%= new_trip_album_path(@trip) %>" rel="#album-form-overlay">Add album</a></div>
  <% end %>
</div>

<div id="trip-head">
	<% if @viewer_is_owner %>
	<h1><%= @trip.title %></h1>
	<% else %>
	<h1><%= @trip.user.username.capitalize %>'s Trip To</h1>
	<% end %>
	<h2><%= @trip.destination_city.blank? ? @trip.destination : @trip.destination_city + ', ' + @trip.destination_state %></h2>
	
</div>
<div id="trip-map">
	<div id="map_canvas" style="width:690px; height:450px;"></div>
</div>
<div id="trip-info">

  <div id="side_links">
    <% if @viewer_is_owner %>
    <div class="button"><a href="<%= new_trip_album_path(@trip) %>" rel="#album-form-overlay">Add album</a></div>
    <% end %>
  </div>

	<div id="itenerary">
		<h3><%= @viewer_is_owner ? image_tag('your-profile.png') :  @trip.user.username.capitalize + "'s Photos"%></h3>

		<div class="nav">
			<!--<%= image_tag "left-arrow.png", {:class => 'back prev browse right'} %>-->
			<ul class="tabs">
				<li class="photo"></li>
				<!--<li class="journal"></li> -->
			</ul>
			<!--<%= image_tag 'right-arrow.png', {:class => 'forward next browse left'} %>-->
		</div>
		<div style="clear: left;"></div>
		<div class="tab-panes">
			<!-- Albums -->
			<div class="albums">
        <%= render @trip.albums %>

        <% if (@trip.albums.empty? && @viewer_is_owner) %>
          <a href="<%= new_trip_album_path(@trip) %>" rel="#album-form-overlay">Add album</a>
        <% end %>

        <br clear="both" />
      </div>
      <!-- End Albums -->

      <!-- Journals -->
			<div class="daily-view">
				<div class="day">
					<div class="head">
						October 19
					</div>
					<div class="body">

					</div>
				</div>
			</div>
			<!-- End Journals -->
		</div>
	</div>
</div>

<div id="album-form-overlay" class="overlay" style="display:none">
	<!-- the external content is loaded inside this tag -->
	<div class="contentWrap"></div>
</div>


<script type="text/javascript">

var geocoder;
var map;
var marker;
   
function initialize(){
  var latlng = new google.maps.LatLng(<%= @trip.latitude %>, <%= @trip.longitude %>);
  var options = {
    scrollwheel: false,
    zoom: 11,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
       
  map = new google.maps.Map(document.getElementById("map_canvas"), options);
       
  //GEOCODER
  geocoder = new google.maps.Geocoder();
  
	  var mainMarker = new google.maps.Marker({
        position: latlng, 
        map: map, 
        title:"<%= @trip.destination %>"
	  });
  var bounds = new google.maps.LatLngBounds();
	  
  <% @trip.events.mapped.each do |place| %>
	  myLatLng = new google.maps.LatLng(<%= place.latitude %>, <%= place.longitude %>);
	  var marker = new google.maps.Marker({
        position: myLatLng, 
        map: map, 
        title:"<%= place.title %>"
	  }); 
      bounds.extend(myLatLng);
      map.fitBounds(bounds);
  <% end %>
  
  $("#map_canvas").append('<span class="hide_map"><a href="javascript://" id="hide_map_link">hide map</a></span>');
}

$(document).ready(function() {
         
  initialize();
  
  $("#hide_map_link").toggle(function(){
	$("#map_canvas").elapsor({
      color:'#fff',
      opacity:70
	});
	$("#map_canvas").animate({height:"50px"},1000);
	$("#map_canvas span a").html("show map");
  }, function(){
	$("#map_canvas").hideElapsor();
	$("#map_canvas").animate({height:"450px"},1000);
	$("#map_canvas span a").html("hide map");
  });
  
  
  $("#hide_map_link").click();
});

</script>

app/views/albums/new.html.erb
<div class="header">
  <%= image_tag 'create-album-header.png', :class => 'title' %>
  <a href="#" onclick="$open_overlay.close(); return false;"><%= image_tag 'event-form-close.png' %></a>
</div>

<%= form_for([@trip, @album], :html => {:class => 'album_form'}) do |f| %>
<%= render 'form', :f => f %>
<% end %>

app/views/albums/show.html.erb
<style type="text/css">
#content {
  min-height: 600px;
}
</style>
<%= javascript_include_tag 'album_form.js' %>
<div id="sidebar">
  <div id="share_it">
    <%= link_to image_tag("plan-it.png"), trip_url(@trip) %>
  </div>
</div>

<div id="trip-head">
	<h1><%= @trip.title %></h1>
	<h2><%= @trip.destination_city.blank? ? @trip.destination : @trip.destination_city + ', ' + @trip.destination_state %></h2>
</div>
<div id="trip-map">
	<div id="map_canvas" style="width:690px; height:450px;"></div>
</div>
<div id="trip-info">
  <div id="side_links">
    
    <div class="button"><a href="<%= new_trip_album_image_path(@trip, @album) %>" rel="#album-form-overlay">Add images</a></div>
  </div>

	<div id="itenerary">
		<h3><%= image_tag 'your-profile.png' %></h3>

		<div class="nav">
			<!--<%= image_tag "left-arrow.png", {:class => 'back prev browse right'} %> -->
			<ul class="tabs">
				<li class="photo"></li>
				<!-- <li class="journal"></li> -->
			</ul>
			<!--<%= image_tag 'right-arrow.png', {:class => 'forward next browse left'} %> -->
		</div>
		<div style="clear: left;"></div>
		<div class="tab-panes">
			<!-- Albums -->
			<div class="albums">

			  <div class="album_info">
			    <div class="back_button"><%= link_to 'Back to galleries', trip_albums_path(@trip) %></div>
          <%= @album.title %><!--<a href="#">Edit</a>-->
          <div class="album_stats">
            <%= @album.images.count %> Photos | 
            <%= @album.created_at.strftime('%B %d, %Y') %>
          </div>
        </div>

        <!--
        <div class="album_permissions">
          
        </div>
        -->

        <% @album.images.each do |image| %>
          <div class="album_image">
            <%= link_to image_tag(image.file.thumb.url), [@trip, @album, image] %>

            <!--
            <div class="image_options">
              <a href="#">add description</a> | 
              <a href="#">delete image</a>
            </div>
            <%= image.description %>
            -->
          </div>
        <% end %>

        <br clear="both" />
        
      </div>
      <!-- End Albums -->

      <!-- Journals -->
			<!--
			<div class="journals">
			</div>
			-->
			<!-- End Journals -->
		</div>
	</div>
</div>

<div id="album-form-overlay" class="overlay" style="display:none">
	<!-- the external content is loaded inside this tag -->
	<div class="contentWrap">
	  
  </div>
</div>

<script type="text/javascript">

var geocoder;
var map;
var marker;
   
function initialize(){
  var latlng = new google.maps.LatLng(<%= @trip.latitude %>, <%= @trip.longitude %>);
  var options = {
    scrollwheel: false,
    zoom: 11,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
       
  map = new google.maps.Map(document.getElementById("map_canvas"), options);
       
  //GEOCODER
  geocoder = new google.maps.Geocoder();
  
	  var mainMarker = new google.maps.Marker({
        position: latlng, 
        map: map, 
        title:"<%= @trip.destination %>"
	  });
  var bounds = new google.maps.LatLngBounds();
	  
  <% @trip.events.mapped.each do |place| %>
	  myLatLng = new google.maps.LatLng(<%= place.latitude %>, <%= place.longitude %>);
	  var marker = new google.maps.Marker({
        position: myLatLng, 
        map: map, 
        title:"<%= place.title %>"
	  }); 
      bounds.extend(myLatLng);
      map.fitBounds(bounds);
  <% end %>
  
  $("#map_canvas").append('<span class="hide_map"><a href="javascript://" id="hide_map_link">hide map</a></span>');
}

$(document).ready(function() {
         
  initialize();
  
  $("#hide_map_link").toggle(function(){
	$("#map_canvas").elapsor({
      color:'#fff',
      opacity:70
	});
	$("#map_canvas").animate({height:"50px"},1000);
	$("#map_canvas span a").html("show map");
  }, function(){
	$("#map_canvas").hideElapsor();
	$("#map_canvas").animate({height:"450px"},1000);
	$("#map_canvas span a").html("hide map");
  });
  
  $("#hide_map_link").click();
});

</script>

app/views/albums/update.js.erb
<% if @album.update_attributes(params[:album]) %>
  $open_overlay.close();
  $("div.overview").html("<%= escape_javascript(render(:partial => 'trips/day_overview'))%>");
  success('Album successfully saved.');
<% else %>
  $('#<%= @album.errors.keys.map {|x| "album_#{x.to_s}" }.join(",#") %>').addClass('field_with_error');
  $('.album_form .error_list').html("<%= raw @album.errors.full_messages.map {|x| "<li>#{x}</li>"}.join %>");
  $('.album_form .errors').show();
<% end %>