config/routes.rb
Planitshareit::Application.routes.draw do
  resources :trips do
    resources :events
    resources :albums do
      resources :images
    end
  end
  
  match 'trips/:trip_id/driving' => "driving_directions#index", :as => "driving"
  match 'trips/:trip_id/day/:day/driving' => "driving_directions#index", :as => "driving"
  match 'public/trips/:trip_id' => "albums#index"
  
  root :to => "pages#index"
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'login' }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plan it. Share it.</title>
  <%= stylesheet_link_tag :all %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery-ui.min', 'jquery.easyAccordion', 'jquery.tools.min', 'jquery.flip.min', 'ternElapse', 'placeholder' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <div id="user_nav">
      <% if user_signed_in? %>
        <%= %w{Hello Hi Hola Bonjour Privet Guten\ Tag Hallo Ciao}.sample %>, <%= current_user.username %>. 
		<%= link_to 'Your Trips', trips_path %>
		<%= link_to 'Create Trip', new_trip_path %>
        <%= link_to "Sign out", destroy_user_session_path %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div>

    <div id="logo"><%= link_to image_tag('logo.png'), '/' %></div>
  </div>

  <div id="content">
    <div id="flash"<%= raw ' style="display:none"' if flash.empty? %>>
      <% flash.each do |f| %>
        <div class="<%= f[0] %>"><%= f[1] %></div>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>